name: 'Hello World'
description: 'Greet someone and save the current date'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The date of the greeting'
runs:
  using: 'docker'
  image: docker://moisesh21/hello-world-docker-action
  args:
    - ${{ inputs.who-to-greet }}
